import {test} from 'node:test';
import assert from 'node:assert/strict';
import {resolveOccurrences} from '../lib/occurrence-resolution';
import {grantTrait,validTrait} from '../lib/traits';
import {recordTravel} from '../lib/progress';
import {transferCharacter} from '../lib/teleport';
const shield:any={id:'s',kind:'status',family:'death_protection',value:'reprieve',lifetime:'single_use',name:'Last Light',description:'A blessing.',source:{x:0,y:0,title:'Home',world:'s',visitId:'v'}};
const player=():any=>({id:'a',name:'A',x:2,y:3,alive:true,deaths:0,furthest:4,badges:[],consumed:[],traits:[shield]});
const p:any={context:{x:3,y:3,distance:4,seed:'s',version:'fieldwork-1',regions:[],occurrences:{death:true,teleport:null,gift:null,challenge:null,option:null}},regions:[],scene:{title:'Edge'},occurrenceText:{choices:[],outcomes:[{key:'death',text:'{character_name} died falling into the chasm.',rescueText:'{protection_name} caught {character_name} and returned them.',badgeTitle:'Fall',badgeDescription:'Fell.',awards:[]}]}};
test('one charge rescues certain death to departure without deaths or badges',()=>{const c=player();recordTravel(c,3,3);const r=resolveOccurrences(c,p,'v');assert.equal(r.character.alive,true);assert.equal(r.character.deaths,0);assert.equal(r.character.badges.length,0);assert.deepEqual([r.character.x,r.character.y],[2,3]);assert.equal(r.character.distanceTotal,1);assert.equal(r.character.traits!.length,0);assert.equal(r.event.kind,'rescued');assert.match(r.event.text,/Last Light caught A/);assert.equal(r.event.stateChanges[0].type,'consumed');const second=resolveOccurrences(r.character,p,'v2');assert.equal(second.character.alive,false);});
test('teleport rescue remembers source even after coordinates change',()=>{const c=player();c.pendingTransport={token:'t',destination:{x:3,y:3},narrative:'Departed',mechanism:'teleport'};const landed=transferCharacter(c,'t',{x:3,y:3,distance:4,title:'Edge'});const r=resolveOccurrences(landed.character,p,'v');assert.deepEqual([r.character.x,r.character.y],[2,3]);assert.equal(r.character.distanceTotal,1);});
test('challenge death consumes protection and prevents later co-located encounters',()=>{const other=structuredClone(p);other.context.occurrences.death=false;other.context.occurrences.challenge={kind:'challenge',requirement:{kind:'defining',value:'Strength'},present:{kind:'none'},absent:{kind:'kill'}};other.context.occurrences.teleport={x:100,y:100};other.context.occurrences.option={policy:'visit',choices:[{kind:'none'},{kind:'kill'}]};other.occurrenceText.outcomes=[{...p.occurrenceText.outcomes[0],key:'challenge:absent'}];const r=resolveOccurrences(player(),other,'v');assert.equal(r.character.alive,true);assert.equal(r.event.kind,'rescued');assert.equal(r.character.pendingTransport,undefined);assert.equal(r.character.pendingOption,undefined);assert.equal(r.character.traits!.length,0);});
test('protection requires single use and replaces an existing charge',()=>{assert.equal(validTrait(shield),true);assert.equal(validTrait({...shield,lifetime:'permanent'}),false);const r=grantTrait([shield],{...shield,id:'second'});assert.equal(r.traits.length,1);assert.equal(r.traits[0].id,'second');});

test('direct and nested option kills consume exactly one safety and preserve choice completion',()=>{for(const outcome of [{kind:'kill'},{kind:'challenge',requirement:{kind:'defining',value:'Strength'},present:{kind:'none'},absent:{kind:'kill'}}]){const other=structuredClone(p);other.context.occurrences={death:false,option:{policy:'life',choices:[{kind:'none'},outcome]}};other.occurrenceText.choices=[{label:'Leave'},{label:'Proceed'}];other.occurrenceText.outcomes=[{...p.occurrenceText.outcomes[0],key:outcome.kind==='challenge'?'option-1:absent':'option-1'}];const c=player();c.x=3;c.previousTile={x:2,y:3};c.pendingOption={key:'s:fieldwork-1:3:3',visit:'v'};const r=resolveOccurrences(c,other,'choose',1);assert.equal(r.event.kind,'rescued');assert.equal(r.character.deaths,0);assert.equal(r.character.badges.length,0);assert.equal(r.character.traits!.length,0);assert.equal(r.character.x,2);assert.equal(r.character.pendingOption,undefined);}});
