import {test} from 'node:test';
import assert from 'node:assert/strict';
import {fieldworkAt} from '../lib/fieldwork';
import {contextFor,exists} from '../lib/world';
import {teleportDestination,definingTraits,occurrencesFor} from '../lib/occurrences';
import {resolveOccurrences} from '../lib/occurrence-resolution';
import type {CellPackage} from '../lib/generation';
import type {Character} from '../lib/rules';
const player=():Character=>({id:'a',name:'Ari',definingTrait:'Faith',x:0,y:0,alive:true,deaths:0,furthest:0,badges:[],consumed:[],traits:[]});
function cell():CellPackage{const context=contextFor('fixture',0,0);context.occurrences={death:false,teleport:null,gift:null,challenge:null,option:null};return {context,regions:[],created:0,pass2Prompt:null,pass2Result:null,imagePackage:null,scene:{title:'Test',description:'',exits:[],visual_brief:'',continuity_facts:[],event_narrative:'',consumed_narrative:'',hostility_narrative:'',death_badge_title:'',death_badge_description:'',honor_badge_title:''},occurrenceText:{death:'{character_name} died.',teleport:'{character_name} departed.',gift:'{character_name} received a gift.',challengePresent:'{character_name} passed.',challengeAbsent:'{character_name} lacked the requirement.',badgeTitle:'Memory',badgeDescription:'A lasting memory.',awardName:'Token',awardDescription:'A token.',choices:[]}};}
test('approved fieldwork supplies all 42 fields and only biome traversal controls existence',()=>{for(const [x,y] of [[0,0],[10,3],[100,100],[1000,0]]){const f=fieldworkAt('fixture',x,y);assert.equal(f.fields.length,42);assert.equal(exists('fixture',x,y),x===0&&y===0||f.explorable);assert.ok(f.fields.every(v=>v.value>=0&&v.value<=1));}});
test('teleport reach grows radially and is deterministic without snapping to grid',()=>{for(const [x,y] of [[0,0],[100,0],[600,800],[10000,0]]){const d=teleportDestination('fixture',x,y);assert.deepEqual(d,teleportDestination('fixture',x,y));assert.ok(Math.hypot(d.x-x,d.y-y)<=Math.max(50,Math.hypot(x,y))+.71);}});
test('challenge checks pre-gift state and gifts require satisfaction',()=>{const p=cell();p.context.occurrences!.challenge={kind:'challenge',requirement:{kind:'defining',value:'Strength'},present:{kind:'none'},absent:{kind:'none'}};p.context.occurrences!.gift={kind:'give',awards:[{kind:'status',family:'blessing',value:'ward',lifetime:'until_death'}],badge:true};const missed=resolveOccurrences(player(),p,'a');assert.equal(missed.character.traits!.length,0);const yes=resolveOccurrences({...player(),definingTrait:'Strength'},p,'b');assert.equal(yes.character.traits!.length,1);assert.equal(yes.character.badges.length,1);assert.match(yes.event.text,/passed.*gift/);});
test('certain death clears choice state, preserves defining trait and permanent state',()=>{const p=cell();p.context.occurrences!.death=true;const c=player();c.optionConsumed=['old'];const r=resolveOccurrences(c,p,'death');assert.equal(r.character.alive,false);assert.equal(r.character.definingTrait,'Faith');assert.equal(r.character.deaths,1);assert.deepEqual(r.character.optionConsumed,[]);assert.equal(r.character.badges[0].kind,'death');});
test('option life policy persists until death and only selected result executes',()=>{const p=cell();p.context.occurrences!.option={policy:'life',choices:[{kind:'badge'},{kind:'kill'}]};p.occurrenceText!.choices=[{label:'Remember',result:'{character_name} remembered.',present:'',absent:''},{label:'Die',result:'{character_name} died.',present:'',absent:''}];const entered=resolveOccurrences(player(),p,'visit').character;const selected=resolveOccurrences(entered,p,'choose',0).character;assert.equal(selected.alive,true);assert.equal(selected.badges.length,1);assert.equal(resolveOccurrences(selected,p,'again').character.pendingOption,undefined);const dead=resolveOccurrences(entered,p,'choose-death',1).character;assert.equal(dead.alive,false);assert.deepEqual(dead.optionConsumed,[]);});
test('occurrence registry has eight traits and deterministic 2–3 choice policies',()=>{assert.equal(definingTraits.length,8);const v={'occurrences.option':1};const a=occurrencesFor('fixture',3,4,v,[]);assert.deepEqual(a,occurrencesFor('fixture',3,4,v,[]));assert.ok([2,3].includes(a.option!.choices.length));});
