"use client";
import {useEffect,useState,useRef} from 'react';
import {registerExplorerTools} from '../lib/webmcp';
import {Compass,ArrowUp,ArrowDown,ArrowLeft,ArrowRight,Skull,Route,Sparkles,Settings2,BookOpen} from 'lucide-react';

export default function Explorer(){
 const [state,setState]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[tab,setTab]=useState('explore'),[name,setName]=useState(''),[inspect,setInspect]=useState<any>(null);
 async function load(id?:string){const r=await fetch('/api/game'+(id?'?character='+encodeURIComponent(id):''));const d:any=await r.json();if(!r.ok)throw Error(d.error||'Could not load your journey.');setState(d);return d;}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 async function act(action:string,extra:Record<string,unknown>={}){
  setBusy(true);setError('');
  try{const r=await fetch('/api/game',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,character:state?.character?.id,requestId:crypto.randomUUID(),...extra})});const d:any=await r.json();if(!r.ok)throw Error(d.error||'The passage could not be opened.');setState(d);setName('');setInspect(null);return d;}
  catch(e:any){setError(e.message);}finally{setBusy(false);}
 }
 async function workshop(){setTab('workshop');try{const r=await fetch('/api/workshop?x='+(state?.character?.x??0)+'&y='+(state?.character?.y??0));const d:any=await r.json();if(!r.ok)throw Error(d.error);setInspect(d);}catch(e:any){setError(e.message);}}
 const actions=useRef({load,act,state});actions.current={load,act,state};
 useEffect(()=>registerExplorerTools(async()=>{const s=await actions.current.load(actions.current.state?.character?.id);return {character:s.character,location:s.cell?.scene,connections:s.connections};},async direction=>{const s=await actions.current.act('move',{direction});if(!s)throw Error('The move did not complete.');return {character:s.character,location:s.cell?.scene,event:s.lastEvent};}),[]);
 async function historyPage(offset:number){try{const r=await fetch('/api/game?character='+state.character.id+'&offset='+offset);const d:any=await r.json();if(!r.ok)throw Error(d.error);setState(d);}catch(e:any){setError(e.message);}}
 const c=state?.character,cell=state?.cell,scene=cell?.scene;
 const arrows:Record<string,any>={north:ArrowUp,west:ArrowLeft,east:ArrowRight,south:ArrowDown};
 const newForm=(first=false)=><form className="new-character" onSubmit={e=>{e.preventDefault();act('create',{name:name||'Wanderer'});}}><label htmlFor="character-name">{first?'What will this world call you?':'Another character, another history'}</label><div><input id="character-name" maxLength={40} value={name} onChange={e=>setName(e.target.value)} placeholder="Your character’s name"/><button className="primary" disabled={busy}>{first?'Begin your journey':'Create character'} <ArrowRight size={16}/></button></div></form>;
 return <main><header className="masthead"><a className="brand" href="/"><Compass size={28}/><span>THE EXPLORER</span></a><nav aria-label="Main"><button className={tab==='explore'?'active':''} onClick={()=>setTab('explore')}>Explore</button><button className={tab==='journal'?'active':''} onClick={()=>setTab('journal')}>Your chronicle</button><button aria-label="Generation workshop" onClick={workshop}><Settings2 size={18}/></button></nav><span className="edition">A WORLD, REMEMBERED</span></header>
 <div className="workspace"><aside className="atlas"><div className="eyebrow">THE NEARBY UNKNOWN</div><div className="map" aria-label="Local dungeon map">{Array.from({length:121},(_,i)=>{const x=(c?.x??0)+i%11-5,y=(c?.y??0)+Math.floor(i/11)-5;const m=state?.map?.find((p:any)=>p.x===x&&p.y===y);return <span key={i} title={'('+x+', '+y+')'} className={['map-cell',m?.exists?'open':'',m?.generated?'known':'',i===60?'current':''].join(' ')}>{i===60?'◆':x===0&&y===0?'⌂':''}</span>;})}</div><div className="map-legend"><span><i className="known-key"/>Remembered</span><span><i/>Unexplored</span></div><div className="coordinates"><span>YOUR COORDINATES</span><strong>{c?.x??0} <em>/</em> {c?.y??0}</strong></div><p className="quiet">Every passage leads somewhere.<br/>Every return leaves a story.</p><div className="atlas-bottom"><Compass size={18}/>Origin · 0 / 0</div></aside>
 <section className="reading-pane">{error&&<div className="error" role="alert">{error}{error.includes('Sign in')&&<a href="/signin-with-chatgpt?return_to=/" target="_top">Sign in with ChatGPT →</a>}<button onClick={()=>load(c?.id).then(()=>setError('')).catch(e=>setError(e.message))}>Refresh</button></div>}
 {tab==='explore'&&<><div className="location-meta"><span className="eyebrow">{c?.alive===false?'A JOURNEY ENDED':!c||(c.x===0&&c.y===0)?'THE PLACE OF RETURN':'FIELD NOTES'}</span><span className="tiny">{cell?'Recorded in the atlas':'Awaiting discovery'}</span></div><h1>{scene?.title??'At the edge of the unwritten'}</h1><div className="region-line">{cell?.regions?.map((r:any)=><span key={r.id}>{r.name}</span>)??<span>Origin · a safe beginning</span>}</div><div className="rule"/><div className="scene">{scene?.description?.split('\n').filter(Boolean).map((p:string,i:number)=><p key={i}>{p}</p>)??<p>The first place has yet to be named. Begin a journey to discover the refuge that will remember every return.</p>}</div>
 {state?.lastEvent&&<div className={'encounter '+(c?.alive===false?'death':'')}><div className="eyebrow">{c?.alive===false?'YOUR LATEST MISADVENTURE':'AN ENCOUNTER'}</div><p>{state.lastEvent.text}</p>{state.lastEvent.newBadge&&<span className="badge-earned">A new distinction: {state.lastEvent.newBadge}</span>}</div>}
 {busy&&<p className="working" role="status"><span/>The next page is being written. New places take a moment.</p>}
 {!c?newForm(true):!c.alive?<button className="primary" disabled={busy} onClick={()=>act('return')}>Return to the origin <Compass size={17}/></button>:<div className="passages"><div className="eyebrow">CHOOSE A PASSAGE</div><div className="passage-buttons">{Object.entries(arrows).map(([d,Icon])=><button disabled={busy||!state?.connections?.[d]} key={d} onClick={()=>act('move',{direction:d})}><Icon size={18}/>{d}</button>)}</div></div>}
 <div className="location-footer"><BookOpen size={16}/><span>{cell?'This place will be here when you return.':'Descriptions are written once, then remembered.'}</span>{cell&&<a href={'/cell/'+(c?.x??0)+'/'+(c?.y??0)}>Link to this place ↗</a>}</div></>}
 {tab==='journal'&&<><div className="eyebrow">A LIFE IN MANY CHAPTERS</div><h1>{c?.name??'Your chronicle'}</h1><p className="lede">The places you found. The ways you fell. The distance you carried with you.</p><div className="badges">{state?.badges?.length?state.badges.map((b:any)=><div className="badge" key={b.id}><Sparkles size={20}/><strong>{b.title}</strong><span>{b.description}</span></div>):<p className="quiet">Your distinctions will appear here. A new way to die always leaves one.</p>}</div><h2>Misadventures</h2><div className="history">{state?.history?.map((h:any)=><article key={h.id}><span className="tiny">{h.x} / {h.y} · {new Date(h.at).toLocaleDateString()}</span><p>{h.text}</p></article>)}</div>{c&&<a href={'/profile/'+c.id}>Link to this character ↗</a>}<div className="passage-buttons">{state?.historyOffset>0&&<button onClick={()=>historyPage(state.historyOffset-25)}>Newer entries</button>}{state?.historyHasMore&&<button onClick={()=>historyPage(state.historyOffset+25)}>Older entries</button>}</div>{newForm()}</>}
 {tab==='workshop'&&<><div className="eyebrow">PRIVATE GENERATION WORKSHOP</div><h1>Behind the place</h1><p className="lede">The numerical world, its language, and the scene they become. Image generation is off.</p><div className="pipeline"><span>01 · Rating descriptions</span>→<span>02 · Connected scene</span>→<span className="quiet">03 · Image, later</span></div>{inspect?<><div className="recipe-list">{inspect.ratings?.map((r:any)=><div key={r.id}><span>{r.id}</span><meter min={0} max={1} value={r.value}/><b>{r.value.toFixed(4)}</b></div>)}</div>{Object.entries({pass1Prompt:'Pass 1 · Prompt',pass1Result:'Pass 1 · Descriptive ratings',pass2Prompt:'Pass 2 · Connected scene prompt',pass2Result:'Pass 2 · Location response',imagePackage:'Future image input · disabled'}).map(([k,label])=><details key={k}><summary>{label}</summary><pre>{JSON.stringify(inspect[k],null,2)??'Generate this cell to populate this stage.'}</pre></details>)}</>:<p className="quiet">Loading generation records…</p>}</>}
 </section><aside className="character-pane"><div className="eyebrow">THE WANDERER</div><div className="character-sigil"><Compass size={38} strokeWidth={1}/></div><h2>{c?.name??'A story not yet begun'}</h2><span className="status">{!c?'At the threshold':c.alive?'Still wandering':'Awaiting return'}</span><div className="stats"><div><Skull size={18}/><span>Total deaths</span><strong>{c?.deaths??0}</strong></div><div><Route size={18}/><span>Furthest distance</span><strong>{c?.furthest?.toFixed(1)??'0.0'}</strong></div><div><Sparkles size={18}/><span>Distinctions</span><strong>{state?.badges?.length??0}</strong></div></div>{state?.characters?.length>1&&<label className="switcher">Your characters<select disabled={busy} value={c?.id} onChange={e=>load(e.target.value).catch(err=>setError(err.message))}>{state.characters.map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}<blockquote>“You keep the stories.<br/>The world keeps the rest.”</blockquote></aside></div><footer className="site-footer"><span>THE EXPLORER</span><span>One world. Countless misadventures.</span><span>Text edition · I</span></footer></main>;
}
