"use client";
import TileMarker from './tile-marker';
import {appPath} from '../lib/app-path';
import {useEffect,useState} from 'react';
import {StateChanges} from './trait-display';
export default function HistoryBrowser({character,initialQuery='',initialOffset=0}:{character:string;initialQuery?:string;initialOffset?:number}){
 const [open,setOpen]=useState(!!initialQuery||initialOffset>0),[q,setQ]=useState(initialQuery),[filter,setFilter]=useState('all'),[offset,setOffset]=useState(initialOffset),[result,setResult]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!open)return;const control=new AbortController();setBusy(true);setError('');const timer=setTimeout(async()=>{try{const params=new URLSearchParams({character,q,filter,offset:String(offset)});const r=await fetch(appPath('/api/history?')+params,{signal:control.signal});const d:any=await r.json();if(!r.ok)throw Error(d.error);setResult(d);}catch(e:any){if(!control.signal.aborted)setError(e.message);}finally{if(!control.signal.aborted)setBusy(false);}},200);return()=>{control.abort();clearTimeout(timer);};},[open,character,q,filter,offset]);
 return <details className="profile-history" open={open} onToggle={e=>setOpen(e.currentTarget.open)}><summary>History</summary><div className="history-controls"><label>Search<input type="search" value={q} maxLength={160} placeholder="Name, status, item, or coordinates" onChange={e=>{setQ(e.target.value);setOffset(0);}}/></label><label>Filter<select value={filter} onChange={e=>{setFilter(e.target.value);setOffset(0);}}>{['all','acquisitions','replacements','losses','uses','deaths','escapes','transport','relics','encounters'].map(f=><option key={f} value={f}>{f[0].toUpperCase()+f.slice(1)}</option>)}</select></label></div>{error&&<p role="alert">{error}</p>}<div aria-busy={busy} className={busy?'history-results pending':'history-results'}>{result?.history.map((h:any)=><article className="encounter" key={h.id}><div className="history-location"><a href={appPath('/cell/')+h.x+'/'+h.y}>{h.x}, {h.y}</a><TileMarker x={h.x} y={h.y}/></div><p>{h.text}</p><StateChanges changes={h.stateChanges}/><time dateTime={new Date(h.at).toISOString()}>{new Date(h.at).toLocaleString()}</time></article>)}{!busy&&result&&!result.history.length&&<p className="muted">No matching history.</p>}</div><div className="buttons">{offset>0&&<button disabled={busy} onClick={()=>setOffset(n=>Math.max(0,n-25))}>Newer</button>}{result?.hasMore&&<button disabled={busy} onClick={()=>setOffset(n=>n+25)}>Older</button>}</div></details>;
}
