import {random} from './noise';

// Broad situations, not scripts: the author supplies participants, form and history.
export const interactionCategories = ['an exchange without currency','an unexpected welcome','a misunderstanding resolved on arrival','a ceremony already in progress','a brief act of assistance','a contest whose result is witnessed','an unusual delivery','a public announcement','a migration crossing the route','a natural process briefly involving the visitor','a machine responding to a presence','a remnant of history put to ordinary use','a curious inspection','a moment of hospitality','a harmless disruption','an accidental discovery with no material reward','a local custom applied to the visitor','a fleeting performance','a mistaken identity','an object or creature completing a small journey','an improbable coincidence','a practical task completed in passing','a disagreement ending unexpectedly','an unusual farewell','a brief shelter shared','a piece of routine maintenance','a patterned sound traced to its source','an animal practicing a learned habit','a useful sign being repaired','a harvest sorted into curious piles','a harmless spill cleaned up','a piece of news changing hands','a crossing politely negotiated','a tiny procession finding its way','an ordinary tool used inventively','a meal being prepared','a game interrupted and resumed','a tired worker taking a break','a lost object returned to its place','a fragment of song overheard','a weather change altering a small routine','a display of craftsmanship','a small disagreement over directions','a quiet act of remembrance','a rehearsal for a practical task','a collection being counted','a temporary shelter being folded away','an old tradition adapted to a new purpose','a creature borrowing a resting place','a harmless mechanical malfunction','a minor repair revealing clever workmanship','a local greeting expressed without words','a burden briefly shared','a seasonal chore observed','an impromptu lesson','a short-lived arrangement made by wind or water'] as const;

export function interactionFor(seed:string,x:number,y:number,v:Record<string,number>){
 const social=['encounters.traveler','encounters.patrol','encounters.caravan','civilization.camp','economy.market','civilization.settlement'].some(id=>v[id]>0);
 const active=['wildlife.herd','wildlife.nest','infrastructure.machine','culture.shrine','supernatural.haunting','culture.arena'].some(id=>v[id]>0);
 if(Math.abs(x)+Math.abs(y)<=2||random(seed,'interaction-occurrence',x,y)> (social?.38:active?.30:.25))return null;
 const category=interactionCategories[Math.floor(random(seed,'interaction-category',x,y)*interactionCategories.length)];
 const modeRoll=random(seed,'interaction-repeat',x,y);
 return {id:'interaction',kind:'interaction',mode:modeRoll<.08?'once_ever':modeRoll<.65?'once_per_character':'every_visit',cause:null,deathId:null,entityId:null,category,
  interpretation:random(seed,'interaction-interpretation',x,y)<.12?'unusual but grounded in the present features':'small, concrete and matter-of-fact',
  outcome:'A brief automatic experience recorded in history. No death, travel, badge, inventory, choice, payment, or lasting world mutation.'};
}
