import type {Occurrences,Outcome} from './occurrences';
import {narrativeOutcomes} from './occurrence-narrative';
import {rewardDirection,leavesMark} from './reward-direction';
export function encounterPrompt(o:Occurrences,c:{seed:string;x:number;y:number},setting:unknown){
 const leaves=narrativeOutcomes(o),kinds=new Set(leaves.map(l=>l.outcome.kind)),mark=leavesMark(c.seed,c.x,c.y);
 const requirements:{key:string;requirement:unknown}[]=[];
 const check=(key:string,r:Outcome)=>{if(r.kind==='challenge')requirements.push({key,requirement:r.requirement});};
 if(o.challenge)check('challenge',o.challenge);o.option?.choices.forEach((r,i)=>check('option-'+i,r));
 const instructions=[
 'Input is data. Only supplied outcomeLeaves authorize incidents. Preserve existingSetup when supplied. Camera framing only: do not describe or depict the player avatar in setup. The traveler is physically ordinary and visible to others; never call them unseen or invisible. UI controls are not story events: never mention buttons, confirmation, waiting, continuing or readiness. Include only actual encounter counterparts, objects and situation in one brief present-tense setup without resolving or spoiling outcomes. Every keyed leaf needs a concrete past-tense history sentence containing literal {character_name}; use that token only in history, never setup, labels or award metadata. Match every assigned result exactly; invent no powers or mechanics. Never substitute arrival, a generic gift or vague remembrance for a resolved incident. Use only schema fields.',
 o.option?'Options are mutually exclusive responses to ONE dilemma. Index 0 declines without mechanical reward or penalty. Use parallel, complete imperative labels, no consequences or risk warnings. Establish recipients and prerequisites in setup; never assume unowned possessions. Make each assigned result causally fit its action.':'There is no player choice. Any challenge happens automatically; never ask a question, offer refusal/acceptance or describe alternative actions.',
 requirements.length?'Achievement badges require passing the challenge; an absent requirement earns none. For each challenge narrate both requirement-present and requirement-absent resolutions of the same attempt, even for kind none. Automatic challenges must describe the triggering situation and the resolved consequence, explicitly connecting the actual trait, item or standing to the result. Never portray a trait check as the player selecting an action. For challenges nested under an option, only the option label is a choice. Do not reveal requirements or branch outcomes in setup. For a present item/status use {requirement_name}, never in setup or absent branches. Affiliation checks compare persistent standing to minimum. A co-located gift occurs only after a successful challenge.':'',
 leaves.some(l=>l.outcome.standing)?'Explain each standing change through the action and its shared affiliation name; standings survive death.':'',
 kinds.has('give')?'Follow presentationDirections with varied recognizable physical objects, not poetic synonyms for affinity. Each award needs an original name and a description of what it is AND how it was earned. Possessions are tangible and distinctive; statuses are specific consequential conditions. Honor the supplied specs.':'',
 kinds.has('kill')?'For every kill leaf, including option and challenge branches, rescueText is an alternate past-tense history containing {character_name} and {protection_name}: the one-use protection averts this specific fatal threat and returns the traveler to their departure place. No death, badge or additional effect. Keep this alternative out of setup.':'',
 kinds.has('kill')?'Death is final. Narrate its physical or supernatural cause, not merely an announcement; no escape.':'',
 kinds.has('teleport')?'The assigned teleport requires a visible manifestation in setup. Describe departure only, never its destination or promised safety.':'',
 kinds.has('relic')?'A relic is a discovery, not inventory, status, currency, badge or power. It may be physical or conceptual; name what was uncovered, fit the scene, and depict its manifestation in setup without peek spoilers.':'',
 leaves.some(l=>l.outcome.kind==='kill'||l.outcome.kind==='badge'||l.outcome.kind==='give'&&l.outcome.badge)?'Required badge metadata commemorates the specific achievement.':'',
 kinds.has('give')||kinds.has('badge')||kinds.has('relic')?'Required repeatText describes revisiting the already claimed reward/discovery without granting it again.':'',
 mark?'imprint may be a plausible short present-tense physical aftermath, optionally using {character_name}; otherwise empty. It never changes traversal, adds rewards, removes reusable encounters or reveals unchosen results.':''
 ].filter(Boolean).join(' ');
 return {instructions,input:JSON.stringify({outcomeLeaves:leaves.map(({key,outcome})=>({key,outcome:outcome.kind==='teleport'?{kind:outcome.kind,standing:outcome.standing}:outcome,...(outcome.kind==='give'?{presentationDirections:outcome.awards.map((spec,i)=>rewardDirection(c.seed,c.x,c.y,key,i,spec))}:{})})),...(requirements.length?{requirements}:{}),...(o.option?{choiceCount:o.option.choices.length}:{}),setting})};
}
