import {distanceMultiplier,distanceIntensity} from './intensity';
import {random} from './noise';

// Broad situations, not scripts: the author supplies participants, form and history.
export const interactionCategories = ['reciprocity', 'recognition', 'miscommunication', 'ritual', 'mutual aid', 'rivalry', 'delivery', 'public information', 'migration', 'ecological interdependence', 'automated response', 'reuse', 'investigation', 'hospitality', 'disruption', 'serendipity', 'social obligation', 'performance', 'identity', 'navigation', 'coincidence', 'labor', 'negotiation', 'parting', 'refuge', 'maintenance', 'communication across distance', 'learned behavior', 'wayfinding', 'seasonality', 'containment', 'rumor', 'access and permission', 'coordination', 'improvisation', 'sustenance', 'play', 'rest', 'restitution', 'oral tradition', 'adaptation', 'craftsmanship', 'disputed knowledge', 'remembrance', 'preparation', 'classification', 'impermanence', 'cultural change', 'territorial coexistence', 'system failure', 'ingenuity', 'nonverbal expression', 'shared responsibility', 'scarcity', 'teaching', 'self-organization', 'mistaken hospitality', 'creative mischief', 'unusual etiquette', 'unexpected spectators', 'a borrowed role', 'a harmless contest', 'an accidental collaboration', 'a migrating tradition', 'a practical joke', 'a small reconciliation', 'collective curiosity', 'an improvised celebration', 'a reversed routine', 'an unlikely messenger', 'an interrupted rehearsal', 'a surprising imitation', 'an exchange of perspectives', 'a fleeting transformation', 'a dispute over meaning', 'a rescue of something small', 'an unexpected welcome', 'a puzzling natural rhythm', 'a beautiful mistake', 'an ordinary task done extraordinarily'] as const;

export function interactionFor(seed:string,x:number,y:number,v:Record<string,number>){
 const social=['encounters.traveler','encounters.patrol','encounters.caravan','civilization.camp','economy.market','civilization.settlement'].some(id=>v[id]>0);
 const active=['wildlife.herd','wildlife.nest','infrastructure.machine','culture.shrine','supernatural.haunting','culture.arena'].some(id=>v[id]>0);
 if(Math.abs(x)+Math.abs(y)<=2||random(seed,'interaction-occurrence',x,y)> Math.min(.65,(social?.48:active?.40:.32)*distanceMultiplier(x,y,2)))return null;
 const category=interactionCategories[Math.floor(random(seed,'interaction-category',x,y)*interactionCategories.length)];
 const modeRoll=random(seed,'interaction-repeat',x,y);
 return {id:'interaction',kind:'interaction',mode:modeRoll<.08?'once_ever':modeRoll<.65?'once_per_character':'every_visit',cause:null,deathId:null,entityId:null,category,
  interpretation:random(seed,'interaction-interpretation',x,y)<Math.min(.75,.30+.5*distanceIntensity(x,y))?'surprising, colorful or gently whimsical; use local features, and let supplied strangeness justify the uncanny':'concrete and distinctive; give the incident a specific action and memorable consequence, even when harmless',
  outcome:'Describe one specific harmless thing the visitor experienced: who or what acted, what physically changed, and how the visitor responded. Resolve the incident in the sentence. No death, travel, badge, inventory, choice, payment, or lasting world mutation.'};
}
