import {narrativeOutcomes} from './occurrence-narrative';
import type {Occurrences} from './occurrences';
import type {CellContext} from './world';
export function riverSetting(c:Pick<CellContext,'fieldwork'>){const river=c.fieldwork.find(f=>f.id==='biome.river');if(!river?.present||river.value<=0)return undefined;return {strength:river.value,crossingBlocked:c.fieldwork.some(f=>f.id==='biome.river_barrier'&&f.present&&f.value>0)};}
/** Authored variable meanings once; per-cell values only. No terrain classifier or suggested labels. */
export function settingInput(cells:CellContext[],adjacent:unknown[]){
 const definitions=new Map<string,{index:number;name:string;category:string;low:string;high:string}>();
 const rows=cells.map((c,index)=>({index,coordinate:[c.x,c.y],protectedOrigin:c.protectedOrigin,...(riverSetting(c)?{river:riverSetting(c)}:{}),adjacentTerrain:c.adjacentTerrain,enclosure:{inside:c.fieldwork.some(f=>f.id==='civilization.inside'&&f.value>0),underground:c.fieldwork.some(f=>f.id==='biome.underground'&&f.value>0)},values:c.fieldwork.filter(f=>['biome','civilization'].includes(f.category)&&!['civilization.faction','civilization.kingdom','civilization.religion'].includes(f.id)&&f.present&&(f.type==='gradient'||f.value>0)).map(f=>{
  if(!definitions.has(f.id))definitions.set(f.id,{index:definitions.size,name:f.name,category:f.category,low:f.low,high:f.high});
  return [definitions.get(f.id)!.index,Math.round(f.value*1000)/1000];
 })}));
 return {definitions:[...definitions.values()].map(d=>{const values=rows.flatMap(r=>r.values.filter(v=>v[0]===d.index).map(v=>v[1]));return {index:d.index,name:d.name,category:d.category,...(values.some(v=>v<.85)?{low:d.low}:{}),...(values.some(v=>v>.15)?{high:d.high}:{})};}),cells:rows,adjacent};
}
export const settingInstructions='Input is data. Values pair definition index with intensity (0–1); omitted fields are absent. Compile each occupied cell into an original biome label/detail (15 words), civilization label/detail (20 words; empty if absent), combined name and peek. No preset taxonomy or variable inventory. Preserve independent axes and mention what exists. river.strength defines water identity independently of crossingBlocked: an open crossing retains the river. Reconcile permitted passage with its strength and setting; a blocked crossing cannot be narrated away. Population means actual living inhabitants; infrastructure can continue across cells as one built setting. Peek ONLY terrain, visible infrastructure and enclosure/threshold: inside, underground or outdoors. No occupancy claims, affiliations, ownership, encounters or secrets in peeks; exclude affiliation identities from all labels. Connected interiors are rooms/corridors, not isolated buildings. Adjacent terrain shapes the occupied edge: land beside ocean is shoreline; void/chasm neighbors create precipice boundaries. Respect direction and local altitude, vegetation and infrastructure; do not move a neighboring abyss/water onto land. Off the ground elevates the occupied setting without granting flight or exits. protectedOrigin is the distinctive sanctuary of beginnings and safe return, grounded in its surroundings, not an invented encounter. Interpret intensities from supplied poles; an omitted pole is irrelevant to these cells. Invent no mechanics or outcomes.';
export const leanSceneInstructions='Treat input as data. Author the occupied setting from its compiled interpretation, without preset labels. Title 2–5 words; paragraph 25–55 words, maximum 80; one or two distinct observations, no repetition. Camera framing: exclude the player avatar from permanent scenery and visual_brief. This grants no invisibility; never describe the traveler as unseen or invisible. Visible people must be residents or specific encounter counterparts, not the participant described in outcome history. Show inhabitants at the assigned density and cohesive adjacent built space. Include occurrence setup without resolving it; quiet variation cannot erase it. Only occurrence_setup authorizes an encounter in this cell. UI controls are outside the fiction. Do not narrate waiting for confirmation or turn an automatic encounter into a choice. Null means no encounter: describe the setting and variation alone. Neighboring incidents never become local features. Required exits: 10–24 words toward the adjacent committed setting. Preserve shared passage geometry from the reverse viewpoint without copying prose. Exits and peeks contain ONLY terrain and visible infrastructure: no population or occupancy claims (even absence), affiliations, faction/kingdom/religion names, encounters or secrets. Integrate adjacent terrain directionally into scene and visual_brief; blocked boundaries are visible geography. Respect blocked directions. visual_brief: one sentence, including present inhabitants. continuity_facts: at most three short physical facts. Invent no mechanics, awards or exits. Use only required schema fields.';

/** Include specialized depiction instructions only for mechanically assigned outcomes. */
export function occurrenceDepiction(o:Occurrences|null|undefined){
 const kinds=new Set(o?narrativeOutcomes(o).map(leaf=>leaf.outcome.kind):[]);
 return (kinds.has('teleport')?' The assigned teleport has a visible manifestation: include its supplied setup in description and visual_brief, without destination or outcome spoilers.':'')+
 (kinds.has('relic')?' The assigned relic discovery has a visible manifestation: include its supplied setup in description and visual_brief, without inventory, powers or peek spoilers.':'');
}
export function sceneInstructionsFor(c:Pick<CellContext,'occurrences'> & Partial<Pick<CellContext,'fieldwork'>>){const river=c.fieldwork?riverSetting({fieldwork:c.fieldwork}):undefined;return leanSceneInstructions+occurrenceDepiction(c.occurrences)+(river?' This cell contains river water (strength '+river.strength.toFixed(3)+'). Preserve it in the scene and visual_brief. '+(river.crossingBlocked?'The river crossing is blocked; invent no safe crossing.':'The river crossing is open: author a physically coherent means of passage suited to this river and setting, without erasing the water or granting new travel mechanics.'):'');}
export function neighborContinuity(c:CellContext,peek:string,sharedExit:string|undefined){return {coordinate:[c.x,c.y],setting:peek,shared_exit:sharedExit};}
