import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
const base='http://localhost:3000';
const sign=await fetch(base+'/signin-with-chatgpt?return_to=/',{redirect:'manual'});
const platform=sign.headers.getSetCookie().map(s=>s.split(';')[0]).join('; ');
let session='';
async function call(path,body,status=200,cookie=platform+'; '+session){
 const r=await fetch(base+path,{method:body?'POST':'GET',headers:{cookie,...(body?{'Content-Type':'application/json',Origin:base}:{})},body:body?JSON.stringify(body):undefined});
 const d=await r.json();assert.equal(r.status,status,JSON.stringify(d));
 return {d,r};
}
const name='Test '+crypto.randomUUID().slice(0,12),password=crypto.randomUUID();
const made=await call('/api/character',{action:'create',name,password});
session=made.r.headers.getSetCookie().find(s=>s.startsWith('explorer_character=')).split(';')[0];
assert.match(made.r.headers.get('set-cookie'),/HttpOnly/);assert.match(made.r.headers.get('set-cookie'),/SameSite=Strict/);
let state=made.d;assert.equal(state.character.x,0);assert.equal(state.character.alive,true);
await call('/api/character',{action:'create',name:name.toUpperCase(),password},409);
const raceName='Race '+crypto.randomUUID().slice(0,12);
const racers=await Promise.all([raceName,raceName.toUpperCase()].map(name=>fetch(base+'/api/character',{method:'POST',headers:{'Content-Type':'application/json',Origin:base,cookie:platform},body:JSON.stringify({action:'create',name,password})})));
assert.deepEqual(racers.map(r=>r.status).sort(),[200,409]);
await call('/api/character',{action:'login',name,password:'wrong-password'},401);
await call('/api/game?character=somebody-else',undefined,403);
await call('/api/game',{action:'move',character:'somebody-else',direction:'east',requestId:crypto.randomUUID()},403);
await call('/api/game',{action:'move',direction:'up',requestId:crypto.randomUUID()},400);
const move={action:'move',direction:'east',requestId:crypto.randomUUID()};
state=(await call('/api/game',move)).d;
const replay=(await call('/api/game',move)).d;
assert.equal(state.character.x,1);assert.equal(replay.character.x,1);assert.equal(state.character.furthest,1);
const workshop=(await call('/api/workshop?x=1&y=0')).d;
assert.equal(workshop.ratings.length,33);assert.ok(workshop.pass1Result.details.length>0);assert.ok(workshop.pass2Result.result.description.length>20);assert.equal(workshop.imagePackage.enabled,false);
assert.equal(workshop.pass2Result.model,'gpt-5.6-luna');
assert.equal(workshop.pass2Result.result.exits.length,Object.values(state.connections).filter(Boolean).length);
assert.ok(workshop.pass2Result.result.description.split(/\s+/).length<=80);
assert.ok(JSON.parse(workshop.pass2Prompt.input).connected_cells.some(n=>n.x===0&&n.y===0&&n.package));
assert.equal('context' in state.cell,false);assert.equal('ratings' in state.cell,false);
const profile=await (await fetch(base+'/profile/'+state.character.id,{headers:{cookie:platform}})).text();
assert.ok(!profile.includes(password));assert.ok(!profile.includes('scrypt$'));
await call('/api/character',{action:'logout'});
await call('/api/game',move,401);assert.equal((await call('/api/game')).d.character,null);
const login=await call('/api/character',{action:'login',name:name.toUpperCase(),password});
assert.equal(login.d.character.id,state.character.id);assert.equal(login.d.character.x,1);
session=login.r.headers.getSetCookie().find(s=>s.startsWith('explorer_character=')).split(';')[0];
await call('/api/character',{action:'logout'});
mkdirSync('outputs',{recursive:true});writeFileSync('outputs/example-cell-package.json',JSON.stringify(workshop,null,2));
console.log('Passed: unique names, hashed-password login, session/logout, authorization, movement, retries, public privacy, and two generation passes.');
