import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
const base='http://localhost:3000';
const sign=await fetch(base+'/signin-with-chatgpt?return_to=/',{redirect:'manual'});
const platform=sign.headers.getSetCookie().map(s=>s.split(';')[0]).join('; ');
let session='';
async function call(path,body,status=200,cookie=platform+'; '+session){
 const r=await fetch(base+path,{method:body?'POST':'GET',headers:{cookie,...(body?{'Content-Type':'application/json',Origin:base}:{})},body:body?JSON.stringify(body):undefined});
 const d=await r.json();assert.equal(r.status,status,JSON.stringify(d));
 return {d,r};
}
const name='Test '+crypto.randomUUID().slice(0,12),password=crypto.randomUUID();
const made=await call('/api/character',{action:'create',name,password});
session=made.r.headers.getSetCookie().find(s=>s.startsWith('explorer_character=')).split(';')[0];
assert.match(made.r.headers.get('set-cookie'),/HttpOnly/);assert.match(made.r.headers.get('set-cookie'),/SameSite=Strict/);
let state=made.d;assert.equal(state.character.x,0);assert.equal(state.character.alive,true);
await call('/api/character',{action:'create',name:name.toUpperCase(),password},409);
const raceName='Race '+crypto.randomUUID().slice(0,12);
const racers=await Promise.all([raceName,raceName.toUpperCase()].map(name=>fetch(base+'/api/character',{method:'POST',headers:{'Content-Type':'application/json',Origin:base,cookie:platform},body:JSON.stringify({action:'create',name,password})})));
assert.deepEqual(racers.map(r=>r.status).sort(),[200,409]);
await call('/api/character',{action:'login',name,password:'wrong-password'},401);
await call('/api/game?character=somebody-else',undefined,403);
await call('/api/game',{action:'move',character:'somebody-else',direction:'east',requestId:crypto.randomUUID()},403);
await call('/api/game',{action:'move',direction:'up',requestId:crypto.randomUUID()},400);
const move={action:'move',direction:'east',requestId:crypto.randomUUID()};
state=(await call('/api/game',move)).d;
const replay=(await call('/api/game',move)).d;
assert.equal(state.character.x,1);assert.equal(replay.character.x,1);assert.equal(state.character.furthest,1);
const beforeView=(await call('/api/game')).d;
const view=await (await fetch(base+'/cell/0/0',{headers:{cookie:platform+'; '+session}})).text();
assert.match(view,/View only/);assert.match(view,/does not move your character/);
const afterView=(await call('/api/game')).d;
assert.deepEqual(afterView.character,beforeView.character);assert.deepEqual(afterView.history,beforeView.history);
assert.equal(state.cell.scene.exits.length+state.cell.scene.blocked.length,4);
assert.ok(state.cell.scene.exits.every(e=>typeof e.glimpse==='string'));
await call('/api/image',{x:99,y:99},403);
await call('/api/image',{x:1,y:0},401,platform);
if(process.env.EXPLORER_TEST_IMAGE==='1'){
 const illustration=(await call('/api/image',{x:1,y:0})).d;
 const repeated=(await call('/api/image',{x:1,y:0})).d;
 assert.equal(repeated.url,illustration.url);
 const r=await fetch(base+illustration.url,{headers:{cookie:platform}});
 assert.equal(r.status,200);assert.equal(r.headers.get('content-type'),'image/webp');
 const bytes=Buffer.from(await r.arrayBuffer());assert.equal(bytes.subarray(8,12).toString(),'WEBP');assert.ok(bytes.length>5000);
 mkdirSync('outputs',{recursive:true});writeFileSync('outputs/test-location.webp',bytes);
 console.log('Verified generated image, persistent recall, and read-only image serving.');
}
const workshop=(await call('/api/workshop?x=1&y=0')).d;
assert.equal(workshop.ratings.length,74);assert.ok(workshop.pass1Result.details.length>0);assert.ok(workshop.pass2Result.result.description.length>20);assert.ok(workshop.imagePackage.enabled||workshop.imagePackage.model==='gpt-image-2');
assert.equal(workshop.pass2Result.model,'gpt-5.6-luna');
assert.equal(workshop.pass2Result.result.exits.length,Object.values(state.connections).filter(Boolean).length);
assert.ok(workshop.pass2Result.result.description.split(/\s+/).length<=80);
assert.ok(JSON.parse(workshop.pass2Prompt.input).connected_cells.some(n=>n.x===0&&n.y===0&&n.package));
assert.equal('context' in state.cell,false);assert.equal('ratings' in state.cell,false);
const profile=await (await fetch(base+'/profile/'+state.character.id,{headers:{cookie:platform}})).text();
assert.ok(!profile.includes(password));assert.ok(!profile.includes('scrypt$'));
assert.match(profile,/<details[^>]*class="profile-history"[^>]*>/);
assert.doesNotMatch(profile,/<details[^>]*class="profile-history"[^>]*\sopen(?:=|\s|>)/);
assert.ok(profile.indexOf('Badges</h2>')<profile.indexOf('History</summary>'));
await call('/api/character',{action:'logout'});
await call('/api/game',move,401);assert.equal((await call('/api/game')).d.character,null);
const login=await call('/api/character',{action:'login',name:name.toUpperCase(),password});
assert.equal(login.d.character.id,state.character.id);assert.equal(login.d.character.x,1);
session=login.r.headers.getSetCookie().find(s=>s.startsWith('explorer_character=')).split(';')[0];
await call('/api/character',{action:'logout'});
mkdirSync('outputs',{recursive:true});writeFileSync('outputs/example-cell-package.json',JSON.stringify(workshop,null,2));
console.log('Passed: unique names, hashed-password login, session/logout, authorization, movement, retries, public privacy, and two generation passes.');
